name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Display Maven version
      run: mvn -v

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests and generate coverage report
      run: mvn test jacoco:report

    - name: Run SonarCloud scan
      uses: sonarsource/sonarcloud-github-action@v2.1.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/site
