name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Display Maven version
      run: mvn -v
      working-directory: ./java-ci-pipeline

   - name: Build with Maven
      run: mvn clean install
      working-directory: ./java-ci-pipeline

    - name: Run tests
      run: mvn test
      working-directory: ./java-ci-pipeline

    - name: Run SonarCloud scan
      uses: sonarsource/sonarcloud-github-action@v2.1.0
      env:
        token: ${{ secrets.SONAR_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
          token: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/site
