name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Display Maven version
      run: mvn -v

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

    - name: Run SonarCloud scan
      uses: sonarsource/sonarcloud-github-action@v1.5
      with:
        projectKey: espuls
        organization: Erick Puls
        token: e3de436ba1fcb27a17e5f1f891298f2adaa3e854

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/site
